backend:
  name: github
  repo: espressohouseco/espressohouse-menu
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "منوی اسپرسو هاوس"
    files:
      - label: "فایل منوی اصلی"
        name: "main_menu"
        file: "index.html"
        fields:
          - {label: "نوشیدنی گرم", name: "hot_drinks", widget: "list", fields: [
              {label: "نام فارسی", name: "fa", widget: "string"},
              {label: "نام انگلیسی", name: "en", widget: "string"},
              {label: "توضیح", name: "desc", widget: "string", required: false},
              {label: "قیمت", name: "price", widget: "string"},
              {label: "تصویر", name: "image", widget: "image"}
            ]}
          - {label: "نوشیدنی سرد", name: "cold_drinks", widget: "list", fields: [
              {label: "نام فارسی", name: "fa", widget: "string"},
              {label: "نام انگلیسی", name: "en", widget: "string"},
              {label: "توضیح", name: "desc", widget: "string", required: false},
              {label: "قیمت", name: "price", widget: "string"},
              {label: "تصویر", name: "image", widget: "image"}
            ]}
          - {label: "کیک", name: "cakes", widget: "list", fields: [
              {label: "نام فارسی", name: "fa", widget: "string"},
              {label: "نام انگلیسی", name: "en", widget: "string"},
              {label: "قیمت", name: "price", widget: "string"},
              {label: "تصویر", name: "image", widget: "image"}
            ]}
          - {label: "ساندویچ", name: "sandwiches", widget: "list", fields: [
              {label: "نام فارسی", name: "fa", widget: "string"},
              {label: "نام انگلیسی", name: "en", widget: "string"},
              {label: "قیمت", name: "price", widget: "string"},
              {label: "تصویر", name: "image", widget: "image"}
            ]}
